use_frameworks! :linkage => :static
workspace 'Demo.xcworkspace'
install! 'cocoapods', :generate_multiple_pod_projects => true
def common
  pod 'KSPlayer', :path => '../', :testspecs => ['Tests']
  pod 'DisplayCriteria', :path => '../'
  pod 'MPVPlayer', :path => '../'
#  pod 'Libass', :path => '../../FFmpegKit'
#  pod 'FFmpegKit', :path => '../../FFmpegKit'
#  pod 'Libmpv', :path => '../../FFmpegKit'
  pod 'Libass',:git => 'git@github.com:TracyPlayer/FFmpegKit.git', :branch => 'lgpl'
  pod 'FFmpegKit',:git => 'git@github.com:TracyPlayer/FFmpegKit.git', :branch => 'lgpl'
  pod 'Libmpv',:git => 'git@github.com:TracyPlayer/FFmpegKit.git', :branch => 'lgpl'
end
target 'demo-iOS' do
  project 'demo-iOS/demo-iOS.xcodeproj'
  platform :ios, 13.0
  common
end

target 'demo-macOS' do
  project 'demo-macOS/demo-macOS.xcodeproj'
  platform :osx, 10.15
  common
end

target 'demo-tvOS' do
  project 'demo-tvOS/demo-tvOS.xcodeproj'
  platform :tvos, 13.0
  common
end

target 'demo-visionOS' do
  project 'demo-visionOS/demo-visionOS.xcodeproj'
  platform :visionos, 1.0
  common
end
