on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buidJob:
    name: buid
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
#      https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version
      - name: Build macOS
        run: swift build
      - name: Build iOS
        run: swift build --sdk `xcrun -sdk iphonesimulator -show-sdk-path` -Xswiftc -target -Xswiftc x86_64-apple-ios13.0-simulator
      - name: Build tvOS
        run: swift build --sdk `xcrun -sdk appletvsimulator -show-sdk-path` -Xswiftc -target -Xswiftc x86_64-apple-tvos13.0-simulator
      - name: Build xrOS
        run: swift build --sdk `xcrun -sdk xrsimulator -show-sdk-path` -Xswiftc -target -Xswiftc x86_64-apple-xros1.0-simulator
      - name: Test
        run: swift test -v
